config/routes.rb
DmWebsite::Application.routes.draw do
  resources :projects

  resources :casestudies

end

app/models/casestudy.rb
class Casestudy < ActiveRecord::Base
  has_many :projects
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :casestudy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/casestudies_controller.rb
class CasestudiesController < ApplicationController
  # GET /casestudies
  # GET /casestudies.json
  def index
    @casestudies = Casestudy.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @casestudies }
    end
  end

  # GET /casestudies/1
  # GET /casestudies/1.json
  def show
    @casestudy = Casestudy.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @casestudy }
    end
  end

  # GET /casestudies/new
  # GET /casestudies/new.json
  def new
    @casestudy = Casestudy.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @casestudy }
    end
  end

  # GET /casestudies/1/edit
  def edit
    @casestudy = Casestudy.find(params[:id])
  end

  # POST /casestudies
  # POST /casestudies.json
  def create
    @casestudy = Casestudy.new(params[:casestudy])

    respond_to do |format|
      if @casestudy.save
        format.html { redirect_to @casestudy, notice: 'Casestudy was successfully created.' }
        format.json { render json: @casestudy, status: :created, location: @casestudy }
      else
        format.html { render action: "new" }
        format.json { render json: @casestudy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /casestudies/1
  # PUT /casestudies/1.json
  def update
    @casestudy = Casestudy.find(params[:id])

    respond_to do |format|
      if @casestudy.update_attributes(params[:casestudy])
        format.html { redirect_to @casestudy, notice: 'Casestudy was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @casestudy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /casestudies/1
  # DELETE /casestudies/1.json
  def destroy
    @casestudy = Casestudy.find(params[:id])
    @casestudy.destroy

    respond_to do |format|
      format.html { redirect_to casestudies_url }
      format.json { head :ok }
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/casestudies_helper.rb
module CasestudiesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/casestudies/_form.html.erb
<%= form_for @casestudy, :html => {:class => "nice"} do |f| %>
  <% if @casestudy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@casestudy.errors.count, "error") %> prohibited this casestudy from being saved:</h2>

      <ul>
      <% @casestudy.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title, :class => "input-text"%>
  </div>
  <div class="field">
    <%= f.label :tagline %>
    <%= f.text_field :tagline, :class => "input-text" %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :goals %>
    <%= f.text_area :goals %>
  </div>
  <div class="field">
    <%= f.label :achievements %>
    <%= f.text_area :achievements %>
  </div>
  <div class="field">
    <%= f.label :results %>
    <%= f.text_area :results %>
  </div>
  <% f.fields_for @project, :project do |r| %>
      <div class="field">
        <%= r.label :title %>
        <%= r.text_field :title %>
      </div>
      <div class="field">
        <%= r.label :description %>
        <%= r.text_area :description %>
      </div>
      <div class="field">
        <%= r.label :artwork %>
        <%= r.text_field :artwork %>
      </div>
      <div class="field">
        <%= r.label :category %>
        <%= r.text_field :category %>
      </div>
  <% end %>
  <div class="actions">
    <%= f.submit 'Save Case Study', :class => "nice small radius blue button" %>
  </div>
<% end %>

app/views/casestudies/edit.html.erb
<h1>Editing casestudy</h1>

<%= render 'form' %>

<%= link_to 'Show', @casestudy %> |
<%= link_to 'Back', casestudies_path %>

app/views/casestudies/index.html.erb
<h1>Listing casestudies</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Tagline</th>
    <th>Description</th>
    <th>Goals</th>
    <th>Achievements</th>
    <th>Results</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @casestudies.each do |casestudy| %>
  <tr>
    <td><%= casestudy.title %></td>
    <td><%= casestudy.tagline %></td>
    <td><%= casestudy.description %></td>
    <td><%= casestudy.goals %></td>
    <td><%= casestudy.achievements %></td>
    <td><%= casestudy.results %></td>
    <td><%= link_to 'Show', casestudy %></td>
    <td><%= link_to 'Edit', edit_casestudy_path(casestudy) %></td>
    <td><%= link_to 'Destroy', casestudy, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Casestudy', new_casestudy_path %>

app/views/casestudies/new.html.erb
<h1>New casestudy</h1>

<%= render 'form' %>

<%= link_to 'Back', casestudies_path %>

app/views/layouts/_footerjs.html.erb
<%= javascript_include_tag "application" %>

app/views/layouts/_head.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DmWebsite</title>
  <link href='http://fonts.googleapis.com/css?family=Lato:300italic,900,700italic,300,400,400italic,900italic,700' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application" %>
  <%= csrf_meta_tags %>
</head>

app/views/layouts/_header-nav.html.erb
<header class="container">
  <div class="row pad-top">
    <div class="columns five">
      <h3>Destination Marketing</h3>
    </div>
    <div class="columns seven">
      <nav id="main-nav">
        <ul>
          <li><a href="#">Case Studies</a></li>
          <li><a href="#">Production Work</a></li>
          <li><a href="#">Our Staff</a></li>
          <li><a href="#">About Us</a></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<%= render "layouts/head"%>
<body>
<%= render "layouts/header-nav"%>
<div class="container">
  <div class="row">
    <%= yield %>
  </div>
</div>
<%= render "layouts/footerjs"%>
</body>
</html>

app/views/projects/_form.html.erb
<%= form_for @project, :html => {:class => "nice" } do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :artwork %><br />
    <%= f.text_field :artwork %>
  </div>
  <div class="field">
    <%= f.label :category %><br />
    <%= f.text_field :category %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Listing projects</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Artwork</th>
    <th>Category</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @projects.each do |project| %>
  <tr>
    <td><%= project.title %></td>
    <td><%= project.description %></td>
    <td><%= project.artwork %></td>
    <td><%= project.category %></td>
    <td><%= link_to 'Show', project %></td>
    <td><%= link_to 'Edit', edit_project_path(project) %></td>
    <td><%= link_to 'Destroy', project, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @project.title %>
</p>

<p>
  <b>Description:</b>
  <%= @project.description %>
</p>

<p>
  <b>Artwork:</b>
  <%= @project.artwork %>
</p>

<p>
  <b>Category:</b>
  <%= @project.category %>
</p>


<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>